<template>
  <div>
    <Section title="踊る善福寺" margin-top="mt-0">
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_1.jpg',
          )
        "
        alt=""
      />
      <p>
        東京の西部に位置する小さな町、善福寺。この映画は、善福寺に暮らし、歌い、踊る人々のドキュメンタリーである。
      </p>
      <p>
        五穀豊穣のための韓国太鼓・チャンゴから、神楽、江戸かっぽれ、コンテンポラリーダンスまで、古今東西のあらゆる踊りが、善福寺を舞台に繰り広げられる。
      </p>
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_2.jpg',
          )
        "
        alt=""
      />
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_3.jpg',
          )
        "
        alt=""
      />
      <p>
        同時に、百年を越える年月を刻みながら、善福寺で暮らす人たちの、日々の営みも映し出される。百年を経て、私たちは何が変わったのか、変わらないのか。
      </p>
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_4.jpg',
          )
        "
        alt=""
      />
      <p>
        百歳を越えてなお現役で働くコーヒー豆店主は、表立って語られることのない、かつてのこの国の姿を今に伝える。
      </p>
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_5.jpg',
          )
        "
        alt=""
      />
      <p>
        映画は、体の奥で眠っていた感覚を揺さぶり、目覚めさせ、あなたはきっと踊りだしたくなるだろう。
      </p>
      <p>
        &lt;主な出演アーティスト&gt;<br />チェ・ジェチョル、堀越彩子、堀越功、飯野竜彦、飯野路代、大杉雅一、無形民俗文化財・石山裕雅社中、橋本フサヨ、かぽーれかぽーれよいとな
      </p>
    </Section>
    <Section title="ホームレスごっこ">
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_6.jpg',
          )
        "
        alt=""
      />
      <p>
        いつから公共の場所は、私たちが自由に使える場所ではなくなってしまったのだろう？<br />ベンチは撤去され、演奏は取り締まられ、野宿者はますます寝床の確保が難しくなっている。
      </p>
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_7.jpg',
          )
        "
        alt=""
      />
      <p>
        スーパーでダンボールを調達し、路上で寝るというパフォーマンスを通じて、作者は公共の空間に自分の居場所を確保しようと試みる。通行人の反応は？<br />警察官に止められるか？<br />ホームレス“見習い”が路上で奮闘するさまは、ユーモラスでさえある。
      </p>
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_8.jpg',
          )
        "
        alt=""
      />
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_9.jpg',
          )
        "
        alt=""
      />
      <p>
        映像に時折混じる肉声は、実際に新宿で路上生活を送る人々の声。怒り、悲しみ、絶望に、あきらめにも似た笑いが混じる。
      </p>
      <img
        :src="
          useAsset(
            'pafshop/dancing_zempukuji__apprentice_homeless_specials_10.jpg',
          )
        "
        alt=""
      />
      <p>公共空間を自分たちの手に取り戻す、小さな抗いの記録。</p>
    </Section>
  </div>
</template>
