name: 'Deploy wordpress'

on:
  repository_dispatch:
    types: [deploy_from_wordpress]

jobs:
  switch-maintenace-mode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Maintenace mode in
        run: | 
          ftp -n <<END
          open ${{ secrets.FTP_SERVER }}
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          put ./html/maintenance/in/.htaccess ${{ secrets.FTP_SERVER_DIR_DEV }}.htaccess
          put ./html/maintenance/in/maintenance.html ${{ secrets.FTP_SERVER_DIR_DEV }}maintenance.html
          END
  deploy-generated-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Make envfile for nuxt
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_NUXT_PUBLIC_API_BASE: ${{ secrets.NUXT_PUBLIC_API_BASE_PRD }}
          envkey_NUXT_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_PRD }}
          file_name: .env
          directory: html
          fail_on_empty: false
          sort_keys: false
      - name: Generate static files
        run: |
          cd html
          bun install
          bun generate
      - name: Sync generated files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR_PRD_JA }}
          local-dir: ./html/.output/public/
          exclude: |
            .htaccess
            maintenance.html
      - name: Maintenace mode out
        run: | 
          ftp -n <<END
          open ${{ secrets.FTP_SERVER }}
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          put ./html/maintenance/out/.htaccess ${{ secrets.FTP_SERVER_DIR_PRD_JA }}.htaccess
          END
 