name: 'Deploy develop'

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  limit-access-to-the-site:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Limit access to the site
        run: |
          ftp -n <<END
          open ${{ secrets.FTP_SERVER }}
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          put ./html/maintenance/out/.htaccess.dev ${{ secrets.FTP_SERVER_DIR_DEV }}.htaccess
          put ./html/maintenance/out/.htpasswd ${{ secrets.FTP_SERVER_DIR_DEV }}.htpasswd
          END
  deploy-static-files:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_IS_DEV: true
          envkey_STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY_TEST }}
          file_name: .env
          directory: html/stripe
          fail_on_empty: false
          sort_keys: false
      - name: Sync files related vendor
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR_DEV }}vendor/
          local-dir: ./html/vendor/
      - name: Sync files related stripe
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR_DEV }}stripe/
          local-dir: ./html/stripe/
      - name: Make envfile for wordpress
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_DISPATCH }}
          file_name: .env
          directory: html/wp/wp-content/themes/petiteadventurefilms
          fail_on_empty: false
          sort_keys: false
      - name: Sync WP theme files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR_DEV }}wp/wp-content/themes/
          local-dir: ./html/wp/wp-content/themes/
  deploy-generated-files:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Make envfile for nuxt
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DEBUG: false
          envkey_NUXT_PUBLIC_API_BASE: ${{ secrets.NUXT_PUBLIC_API_BASE_DEV }}
          envkey_NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NUXT_PUBLIC_STRIPE_PUBLISHABLE_KEY_TEST }}
          file_name: .env
          directory: html
          fail_on_empty: false
          sort_keys: false
      - name: add .env
        run: |
          ftp -n <<END
          open ${{ secrets.FTP_SERVER }}
          user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}
          put ./html/.env ${{ secrets.FTP_SERVER_DIR_PRD_JA }}.env
          END
      - name: Generate static files
        run: |
          cd html
          bun install
          bun generate
      - name: Sync generated files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR_DEV }}
          local-dir: ./html/.output/public/
          exclude: |
            .htaccess
            maintenance.html
            403.html
