on:
  push:
    branches:       
      - develop

jobs:
    FTP-Deploy-Action:
      name: FTP-Deploy-Action
      runs-on: ubuntu-latest 
      steps:
        - uses: actions/checkout@mast
  
        - name: Use Node.js 12.13
          uses: actions/setup-node@v1
          with:
            node-version: '12.13'    
  
        # - name: Build Project
        #   run: |
        #     npm install
        #     npm run generate --if-prese
  
        - name: List output files
          run: ls
  
        - name: FTP-Deploy-Action
          uses: SamKirkland/FTP-Deploy-Action@2.0
          env:
            FTP_SERVER: ${{ secrets.FTP_SERVER }}
            FTP_USERNAME: ${{ secrets.FTP_USERNAM
            FTP_PASSWORD: ${{ secrets.FTP_PASSWOR
            LOCAL_DIR: /
            REMOTE_DIR: /dev.petiteadventurefilms.com  
            ARGS: --delete